POST http://127.0.0.1:8000/signup 
Content-Type: application/json

{ "username": "adam", "password": "Pass1234!", "email": "adam@mail.com" }

###Login Request

POST http://127.0.0.1:8000/admin/login/
Content-Type: application/json

{ "username": "admin", "password": "admin" }

###

GET http://127.0.0.1:8000/test_token 
Content-Type: application/json Authorization: token xxx

{}

###Users api test Request

POST http://127.0.0.1:5000/api/auth
Content-Type: application/json

{ "username": "admin", "password": "admin" }