# Generated by Django 5.0.1 on 2024-01-11 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_militarycamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commanderprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
