# Generated by Django 5.0.1 on 2024-01-09 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_militarycamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militarycamp',
            name='executes_action',
            field=models.CharField(max_length=50, verbose_name='Executes Action'),
        ),
    ]
